apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: database
type: Opaque
stringData:
  # admin user = postgres
  postgres-username: "postgresdb"
  postgres-password: "postgresqlpassword"
  # app user = postgresdb
  password: "postgresqlpassword"
