apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials-apps
  namespace: apps
type: Opaque
stringData:
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "adminpassword"
  RABBITMQ_ERLANG_COOKIE: "supersecretcookie"
