apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials-apps
  namespace: apps
type: Opaque
stringData:
  DB_USER: "postgresdb"
  DB_PASSWORD: "postgresqlpassword"
  postgresPassword: "postgresqlpassword"
  password: "postgresqlpassword"
