apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials-messaging
  namespace: messaging
type: Opaque
stringData:
  username: admin
  password: "adminpassword"
  erlang-cookie: "supersecretcookie"
