apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consumer-chart.fullname" . }}
  labels:
    {{- include "consumer-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "consumer-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "consumer-chart.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.rabbitmq.configMapName }}
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.rabbitmq.configMapName }}
                  key: RABBITMQ_PORT
            - name: QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.rabbitmq.configMapName }}
                  key: QUEUE_NAME

            # RabbitMQ credentials from Secret
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: password

            # DB config from ConfigMap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.database.configMapName }}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.database.configMapName }}
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.database.configMapName }}
                  key: DB_NAME

            # DB credentials from Secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.usernameKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.passwordKey }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
