{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "consumer-chart.fullname" . }}-svc
  labels:
    {{- include "consumer-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "consumer-chart.selectorLabels" . | nindent 4 }}
{{- end }}
