apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-api-chart.fullname" . }}
  labels:
    {{- include "order-api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "order-api-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
