replicaCount: 1

image:
  repository: rontz/rabbitmq-consumer
  pullPolicy: Always
  tag: "dev-1"

rabbitmq:
  configMapName: rabbitmq-config

database:
  configMapName: postgresql-config
  secretName: postgresql-credentials
  usernameKey: postgres-username
  passwordKey: postgres-password
