apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: apps
data:
  ENABLE_PAYMENT_EVENTS_QUEUE: "true"    
  ENABLE_PAYMENT_EVENTS_CONSUMER: "false"
  PAYMENT_EVENTS_TTL_MS: "86400000"

  RABBITMQ_EXCHANGE_EVENTS: "events.topic"
  RABBITMQ_EXCHANGE_DLX: "dlx.direct"
