apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver-chart.fullname" . }}-svc
  labels:
    {{- include "webserver-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "webserver-chart.selectorLabels" . | nindent 4 }}
