
replicaCount: 1

image:
  repository: rontz/rabbitmq-webserver
  pullPolicy: IfNotPresent
  tag: "dev-1"

containerPort: 8080

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  path: "/healthz"
  initialDelaySeconds: 5
  periodSeconds: 10

configMap:
  name: "rabbitmq-config"

rabbitmq:
  secretName: "rabbitmq-credentials"
  usernameKey: "username"
  passwordKey: "password"

autoscaling:
  enabled: false

serviceAccount:
  enabled: false


